# https://docs.docker.com/compose/compose-file/

version: "3"
services:
  
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: metamask
    ports:
      - 27017:27017
    volumes:
      - ./backend/volumes/mongo/db:/data/db
  
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"

  backend:
    build: ./backend/
    ports:
      - "9000:9000"
    links:
      - redis
      - mongodb         